# Only composes the services needed for fullstack development. 
# Meaning you will have to run both backend and frontend yourself.
version: '3.7'
services:
    mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - "27018:27017"