# Composes the services needed for frontend development.
version: '3.7'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"

  api:
    image: moolapi
    environment:
      Environment__Url: localhost:5001
      JWT__Secret: df042c98-01aa-4159-b2e1-b05f4de52747
      MongoDB__StandardConnectionString: mongodb://root:example@mongo:27017/
      MongoDB__DatabaseName: Mool
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_HTTPS_PORT: 5001
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    depends_on:
      - mongo
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ~/.aspnet/https:/https:ro