export const sessionConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGIN_ERROR_HIDE: 'LOGIN_ERROR_HIDE',
    LOG_OUT: 'LOG_OUT',
    RENEW_TOKEN_EXPIRED: 'RENEW_TOKEN_EXPIRED'
};

export const threadsConstants = {
    THREADS_REQUESTED: 'THREADS_REQUESTED',
    THREADS_RECEIVED: 'THREADS_RECEIVED',
    THREAD_LIKE_TOGGLE_REQUESTED: 'THREAD_LIKE_TOGGLE_REQUESTED',
    THREAD_LIKED: 'THREAD_LIKED',
    THREAD_UNLIKED: 'THREAD_UNLIKED',
    THREAD_COMMENTS_TOGGLED: 'THREAD_COMMENTS_TOGGLED',
    THREAD_COMMENT_ORDER_CHANGED: 'THREAD_COMMENT_ORDER_CHANGED',
    THREAD_COMMENTS_REQUESTED: 'THREAD_COMMENTS_REQUESTED',
    THREAD_COMMENTS_RECEIVED: 'THREAD_COMMENTS_RECEIVED',
    THREAD_COMMENT_ADD_REQUESTED: 'THREAD_COMMENT_ADD_REQUESTED',
    THREAD_COMMENT_ADDED: 'THREAD_COMMENT_ADDED',
    THREAD_COMMENT_LIKE_TOGGLE_REQUESTED: 'THREAD_COMMENT_LIKE_TOGGLE_REQUESTED',
};

export const commentsConstants = {
    COMMENT_LIKED: 'COMMENT_LIKED',
    COMMENT_UNLIKED: 'COMMENT_UNLIKED'
};